name: Deploy Application

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Test SSH Connectivity
      run: |
        nc -zv 10.6.0.84 22 || echo "Port 22 is not open"

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@10.6.0.84 'bash -s' < deploy.sh
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
