name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known hosts
      run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Test SSH Connectivity
      run: |
        if ! nc -zv ${{ secrets.SERVER_IP }} 22; then
          echo "Error: Cannot connect to server on port 22"
          exit 1
        fi

    - name: Deploy to server
      run: |
        ssh ubuntu@${{ secrets.SERVER_IP }} 'bash -s' < deploy.sh
